---
README.md:
    name: "sprinter-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6d38e78abc422000010/badge.svg)](https://www.versioneye.com/user/projects/53dde6d38e78abc422000010)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-sprinter-service-provider/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-sprinter-service-provider/?branch=master)"
