services:
    sprinter.sprinter_service:
        class: 'ETNA\Sprinter\Services\SprinterService'
        autowire: true
        public: false

    ETNA\Sprinter\Services\SprinterService: '@sprinter.sprinter_service'
